### ISSUE TITLE
After 60 days feed is down, displaying 'Session Expired' 

### ISSUE THREAD

**Issue by baronferguson** [companionstudio/instagram-token-agent#10]
After installing and activating on April 1 it looks like the token never refreshed.

Error: api request error: 190 Error validating access token: Session has expired on Sunday, 31-May-20 10:12:48 PDT. The current time is Monday, 01-Jun-20 08:12:02 PDT.

<img width="745" alt="Screen Shot 2020-06-01 at 12 04 06 PM" src="https://user-images.githubusercontent.com/47697256/83428312-266f3900-a400-11ea-9ea7-49bb59b6eff5.png">

Thanks for any help!

**Comment by magentogetairdev** [comment]
@benjamin-hull 
I am facing same issue
![image](https://user-images.githubusercontent.com/38888659/85259031-f575a780-b485-11ea-871c-e42f380e99a9.png)

**Comment by creatpixinfotech** [comment]
@benjamin-hull 
I am facing same issue, please help me what should I do.
![image](https://user-images.githubusercontent.com/38888659/85259253-5b622f00-b486-11ea-95b4-1c9e6828da16.png)

**Comment by benjamin-hull** [comment]
Hi @baronferguson - sorry for the delayed response: Github just refuses to send me the notifications I want on this repo!

Did this originally work and then stop? If so, then it sounds like there's an issue with the scheduling service which is supposed to refresh the token. Are you able to email me (available in my profile) with the specific address of your agent on Heroku so I can see more?

**Comment by benjamin-hull** [comment]
Another thing to check, for both @baronferguson and @creatpixinfotech - if you log into your Heroku dashboard, and go to the _Resources_ tab for your app, you should see 3 Add-ons: Heroku Postgres, MemCachier and Temporize Scheduler. Could you just confirm that all three are there?

If so, click the 'Temporize Scheduler' link to open the scheduling dashboard - you should see a single entry in the 'Events' table, showing the recurring event and the time it's supposed to re-run.

**Comment by creatpixinfotech** [comment]
@benjamin-hull 
Thanks Ben. We will do it and let you know our feed is working or now.

**Comment by baronferguson** [comment]
Hi @benjamin-hull thank you for looking into this! I really appreciate all your hard work and for continuing to follow up.

All three Add-ons are present: 1) Heroku Postgres, 2) MemCachier, and 3) Temporize Scheduler.

Within Temporize everything looks the same as your example as well as the single event. I will email you the app url. 

![add-ons](https://user-images.githubusercontent.com/47697256/85625733-e6375b00-b639-11ea-9679-1431f825acd8.jpg)

**Comment by nburt** [comment]
I'm having the same problem. I tried triggering manually and checked heroku logs and looks like the refresh url is throwing an exception:

line: `/app/lib/instagram_token_agent/client.rb:45:in `signature'`
`#<NoMethodError: undefined method `webhook_secret' for nil:NilClass>`

So seems like "app" in https://github.com/companionstudio/instagram-token-agent/blob/master/app.rb#L148 is nil. Should that be "settings" instead?

**Comment by adaptpatrick** [comment]
@benjamin-hull similar to @nburt my cron is also triggering a 500 error: 
![image](https://user-images.githubusercontent.com/13484425/87408653-ae2d9300-c5bb-11ea-8d86-a28491e36b53.png)

When I click to find out more I see the following:
![image](https://user-images.githubusercontent.com/13484425/87408758-dcab6e00-c5bb-11ea-8954-b57d17be87ce.png)

I would really appreciate it if there's anything that can be done to resolve any issues with this. It's a fantastic tool which we're using more & more. 

If there's any more detail I can provide, please let me know!

**Comment by mariohoyos92** [comment]
> @benjamin-hull similar to @nburt my cron is also triggering a 500 error:
> ![image](https://user-images.githubusercontent.com/13484425/87408653-ae2d9300-c5bb-11ea-8d86-a28491e36b53.png)
> 
> When I click to find out more I see the following:
> ![image](https://user-images.githubusercontent.com/13484425/87408758-dcab6e00-c5bb-11ea-8954-b57d17be87ce.png)
> 
> I would really appreciate it if there's anything that can be done to resolve any issues with this. It's a fantastic tool which we're using more & more.
> 
> If there's any more detail I can provide, please let me know!

Facing this same issue! I love this app so far, but unsure of how to get it back to being operational. The issue sounds the exact same as the others in this thread.

**Comment by Liopia** [comment]
I'm experiencing the same issue but have no new information to add. My screenshot would look very similar to @adaptpatrick and @mariohoyos92 (error 500 with "An unhandled lowlevel error occurred." in the response body). I really appreciate the work done on this project!

**Comment by ckarpinski** [comment]
I am having the same issue. Got this set up and working great on June 1 and today it stopped working. My temporizer looks just like the screenshots above. I have all 3 of the resources named above.

**Comment by benjamin-hull** [comment]
Hi all - This is fixed as part of issue #21. If you update your agent to 1.0.2, this will be resolved.

[Instructions for updating your app](https://github.com/companionstudio/instagram-token-agent/wiki/Updating-your-token-agent-on-Heroku) are available in the wiki.
