### ISSUE TITLE
Enforce ALLOWED_DOMAINS list

### ISSUE THREAD

**Issue by benjamin-hull** [companionstudio/instagram-token-agent#15]
To address #13, the agent should set a default ALLOWED_DOMAINS list (to its own domain @ herokuapp.com), and require the user to set their domain. This is to reduce the scope of the apps availability.

**Comment by gchaimovitz** [comment]
I'm sorry for my ignorance but does this resolve the issue?  How do I reinstall the app to make it work.  So far, in chrome inspector I'm seeing an error that token.js doesn't exist.
