### ISSUE TITLE
Creating heroku app fails

### ISSUE THREAD

**Issue by RobinOTYS** [companionstudio/instagram-token-agent#16]
This morning I started with the new Insta API and I found this token agent. It looks very helpful, however, I stumbled upon some problems. I followed the steps given to create a Heroku app but every time I see these errors:

> Create app: App creation failed. Please ensure you have valid values in the above form fields.

> Configure environment: Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at https://heroku.com/verify

I do not want to add my payment details to verify my account as I am just trying to figure out how to implement the new Insta API. And besides that, I cannot find any pricing information on the Heroku website. Is there any way to skip this "verify your account" thing?

I am sure I filled in all the fields as explained in the steps given. The "Starting token" is the very long token that can be generated at the "User Token Generator" section? Right?

**Comment by ferremek** [comment]
@RobinOTYS There are no Heroku costs associated with deploying the Instagam Token Agent as it makes use of a free dyno. And I don't think there will be another way of verifying your account other than adding your credit card information.

**Comment by RobinOTYS** [comment]
OK, as I understand there is no way around the verification with CC, I've added CC credentials :)

**Comment by benjamin-hull** [comment]
Great, thanks for your help @ferremek .

I'm currently waiting on a review of the app by Heroku - please see #13 for status there.
