### ISSUE TITLE
After deploying, there's no app

### ISSUE THREAD

**Issue by angelogiomateo** [companionstudio/instagram-token-agent#17]
When I try to access https://agminsta.herokuapp.com/, it says "There's nothing here, yet"
So when I try to use instafeed.js, it can't find https://agminsta.herokuapp.com/token.js.

What should I do?

**Comment by sandervanh** [comment]
Got the same issue!

**Comment by RobinOTYS** [comment]
Same issue here https://robin-insta-test.herokuapp.com/

**Comment by wearegoose** [comment]
Same issue here.

**Comment by hhermsen** [comment]
Probably related to app being suspended by Heroku https://github.com/companionstudio/instagram-token-agent/issues/13

**Comment by RobinOTYS** [comment]
> Probably related to app being suspended by Heroku #13

I understand but is someone working on the app being approved by Heroku? Because now nobody can use this app (and the Instagram feed).

**Comment by TimothyGilman** [comment]
As of July 9, Heroku support said they were waiting to hear back from the app developer.

**Comment by nicholasroubal** [comment]
Same issue here... worked for the initial View and then went blank

**Comment by qsad** [comment]
Same issue!

**Comment by j-bn** [comment]
Same here

**Comment by SILENTVOICE976** [comment]
same issue, any updates?

**Comment by garethmorgans** [comment]
Same!

**Comment by garethmorgans** [comment]
@SILENTVOICE976 @j-bn @qsad @nicholasroubal and anyone else this is affecting:

There's a different service available called instant-tokens.com. There are some examples on how to implement on this thread:
https://github.com/stevenschobert/instafeed.js/issues/654

Hope this helps!

**Comment by benjamin-hull** [comment]
Hey everyone - I'm going to close this so we can continue discussion over in #13 (it's the same issue).
