### ISSUE TITLE
Error from Instagram: The access_token provided is invalid.

### ISSUE THREAD

**Issue by bryant22** [companionstudio/instagram-token-agent#20]
When trying to use the instafeed.js, I get the following error: "Error from Instagram: The access_token provided is invalid."
I have created multiple tokens and entered them into my heroku app, but it just doesnt seem to work. Now I would think that this is because of an issue with my app setup in facebook, however, in my heroku app it does seem to load the last post from my instagram feed perfectly..

<img width="762" alt="Screenshot 2020-08-01 at 08 21 45" src="https://user-images.githubusercontent.com/34067963/89095670-6e92e380-d3d0-11ea-824f-de55d0e70156.png">

here is my code:
`<script src='https://livefeed-gabrielkessler.herokuapp.com/token.js'></script>
	<script type="text/javascript" src="js/instafeed.min.js"></script>
	<script type="text/javascript">
	    var userFeed = new Instafeed({
	        accessToken: InstagramToken,
	        limit: '9',
	        sortBy: 'most-recent',
	        resolution: 'low_resolution',
	        template: '<div class="col-lg-4 instaimg ori-{{orientation}}"><a href="{{link}}" title="{{caption}}" target="_blank"><img src="{{image}}" alt="Bitte stellen Sie eine sichere Verbindung her!" class="img-fluid"/></a></div>'
	    });
	    userFeed.run();
	</script>`

Facebook does tell me to verify my business, but I thought the app should also work like this since I have setup a tester..

- ALLOWED_DOMAINS is correctly set, as well as the STARTING_TOKEN

**Info:**
 - OS:  iOS
 - Browser chrome, safari and every other browser

**Comment by benjamin-hull** [comment]
Hi @bryant22 - like you said, the fact that you can see the post in the token agent screen means you must have a valid access token. Could you just confirm that you're using v2 of instafeed.js ? Some of those options you have - `resolution`, `limit`, etc. - aren't available in v2, which makes me wonder if you're using instafeed v1 still?

**Comment by bryant22** [comment]
Yes, I had updated the instafeed.min.js to version 2.0. in the [migration guide](https://github.com/stevenschobert/instafeed.js/wiki/Version-2-migration-guide) it seems that `limit` is still available, but yes, `resolution` and `sortBy` have been removed. Unfortunately, even removing all of these options have not resolved the `Uncaught Error: Error from Instagram: The access_token provided is invalid.` error

**Comment by bryant22** [comment]
Alright, I was able to fix it.

1. limit now has to be given a number, not a string containing the number
2. I foolishly loaded the script before the #instafeed was defined -.- (thats why scripts should always be loaded in the footer)
3. `resolution` and `sortBy` had to be removed
