### ISSUE TITLE
ALLOWED_DOMAINS works only for the first domain in the list

### ISSUE THREAD

**Issue by niklaspollonen** [companionstudio/instagram-token-agent#23]
**Describe the bug**
When adding multiple ALLOWED_DOMAINS only the first one is used. The site is using redirection to the first domain and I do not have direct access to the server.

error:
Access to XMLHttpRequest at 'https://appname.herokuapp.com/token.json' from origin 'https://domain2.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://domain.com' that is not equal to the supplied origin.

**To Reproduce**
1. Add domains with whitespaces in between "domain1.com domain2.com www.domain.com something.domain.com".
2. Go to the site using the domains above. 

**Expected behavior**
Should work on all pages

**Comment by AlexanderBachSchmidt** [comment]
I'm having the exact same issue and have tried everything. Even with only one domain in the list, it doesn't work.
@niklaspollonen Were you able to fix it?

**Comment by niklaspollonen** [comment]
I didn't have time to find a proper solution so I reverted back to an older version of token agent that sets the ALLOWED_DOMAINS to "*" if its left undefined, making the token available to all domains. This is not as secure but I will try to find a better solution at some point in the future.

**Comment by fuego161** [comment]
Yeah, I can't seem to get this work using one address either. Please ping if a solution arises.

**Comment by benjamin-hull** [comment]
Hi all,

Could you try a fresh deployment from the button on the starting-environment branch here? https://github.com/companionstudio/instagram-token-agent/tree/starting-environment - it will ask for ALLOWED_DOMAINS on deploy, and includes some nicer error handling logging in case anything goes wrong during the deployment. It also explicitly supports multiple domains separated with spaces.

@niklaspollonen, specifically regarding the redirection issue, I haven't tested that arrangement with CORS myself, but I can't see any reason it shouldn't work. Let me know your results, please!

Thanks all!

**Comment by benjamin-hull** [comment]
This should be resolved in version 1.0.3 - please re-open/comment if you have any further issues.
