### ISSUE TITLE
Help with initial Heroku config

### ISSUE THREAD

**Issue by lucidprojects** [companionstudio/instagram-token-agent#24]
I had this working since June but it stopped working and before I found your solution [here](https://github.com/companionstudio/instagram-token-agent/wiki/Updating-your-token-agent-on-Heroku) I had already deleted my previously working Heroku app to start over.

Now when I go through the how to and deploy I am shown this screen when testing my app

https://dezshredder-instagram-token-08.herokuapp.com

![heroku](https://user-images.githubusercontent.com/50380056/91458320-6012dd00-e853-11ea-9deb-b21f58db1a98.png)

But when I go to settings I don't see anything about an INSTAGRAM_TOKEN only STARTING_TOKEN which I updated with my token.  Redeploying doesn't seem to make a difference.

![heroku](https://user-images.githubusercontent.com/50380056/91459323-82592a80-e854-11ea-8107-63de246315c4.png)

However using the same token from STARTING_TOKEN allows me to access my instagram feed when running the below curl cmd.

```curl -X GET   'https://graph.instagram.com/17900177464472031?fields=id,media_type,media_url,username,timestamp&access_token=[STARTING_TOKEN]' | python -m json.tool```

**Comment by sandervanh** [comment]
You need to add to that list: 
Config var: ALLOWED_DOMAINS
Value: yourdomain.com

As the welcome screen says, your token is OK.

**Comment by lucidprojects** [comment]
OH! 🤦‍♂️ 

That did it.

Thanks you!
