### ISSUE TITLE
problem installing on heroku

### ISSUE THREAD

**Issue by andy-bourgeois** [companionstudio/instagram-token-agent#25]
I am trying to install on heroku following the instructions in the README.md file.

After clicking "deploy app" I get to the last section "Run scripts & scale dynos" and it fails with the error message "postdeploy exit code was not 0".  Here is the full log:

```
Rails backports are deprecated.

DEPRECATION WARNING: Setting `ActiveRecord::Base.configurations` with `[]=` is deprecated. Use `ActiveRecord::Base.configurations=` directly to set the configurations instead. (called from <top (required)> at /app/app.rb:5)

DEPRECATION WARNING: Setting `ActiveRecord::Base.configurations` with `[]=` is deprecated. Use `ActiveRecord::Base.configurations=` directly to set the configurations instead. (called from <class:App> at /app/app.rb:10)

rake aborted!

TypeError: can't convert nil into an exact number

/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/time/calculations.rb:264:in `+'

/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/time/calculations.rb:264:in `plus_with_duration'

/app/lib/instagram_token_agent/client.rb:24:in `refresh'

lib/tasks/setup.rake:19:in `block in <top (required)>'

/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'

/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'

/app/vendor/bundle/bin/bundle:104:in `load'

/app/vendor/bundle/bin/bundle:104:in `<main>'

Tasks: TOP => setup

(See full trace by running task with --trace)
```

**Comment by devGuerra** [comment]
Same problem here

**Comment by adaptpatrick** [comment]
Also getting this issue, frustratingly... 

Additionally the "easy deploy" button in the readme file wasn't working for me either. It results in the following URL: `https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2F&template=https%3A%2F%2Fgithub.com%2F` but I figured out it should be `https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fcompanionstudio%2Finstagram-token-agent&template=https%3A%2F%2Fgithub.com%2Fcompanionstudio%2Finstagram-token-agent`

Any help you can provide @benjamin-hull would be much appreciated! 🙏

**Comment by fmcausby** [comment]
I'm getting the same error as the original post. Any update on this?

**Comment by soyfedemunoz** [comment]
Same problem here, any solution to this?

**Comment by flyingwip** [comment]
I also ran into this problem

**Comment by benjamin-hull** [comment]
Hi all - could you try deploying from the button on the `starting-environment` branch here? https://github.com/companionstudio/instagram-token-agent/tree/starting-environment - it will ask for ALLOWED_DOMAINS on deploy, and includes some nicer error handling logging in case anything goes wrong during the deployment.

Let me know how that goes!

**Comment by adaptpatrick** [comment]
Thanks @benjamin-hull, it looks like the button on that branch still isn't working quite correctly (as per my previous comment), however I've figured out the correct URL for others should be:

`https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fcompanionstudio%2Finstagram-token-agent%2Ftree%2Fstarting-environment&template=https%3A%2F%2Fgithub.com%2Fcompanionstudio%2Finstagram-token-agent%2Ftree%2Fstarting-environment`

Additionally I'm now getting the following error at build:

```
-----> Ruby app detected
-----> Installing bundler 2.0.2
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.6.5
-----> Installing dependencies using bundler 2.0.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Your Ruby version is 2.6.5, but your Gemfile specified 2.6.6
       Bundler Output: Your Ruby version is 2.6.5, but your Gemfile specified 2.6.6
 !
 !     Failed to install gems via Bundler.
 !     Detected a mismatch between your Ruby version installed and
 !     Ruby version specified in Gemfile or Gemfile.lock. You can
 !     correct this by running:
 !     
 !     $ bundle update --ruby
 !     $ git add Gemfile.lock
 !     $ git commit -m "update ruby version"
 !     
 !     If this does not solve the issue please see this documentation:
 !     
 !     https://devcenter.heroku.com/articles/ruby-versions#your-ruby-version-is-x-but-your-gemfile-specified-y
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```
Could you take another look at your earliest convenience, please? 🙏. Thanks!

**Comment by benjamin-hull** [comment]
Hi @adaptpatrick - Oops, that was a silly one on my part. Give it another try now.

The deploy button URL is a bit of a red herring though, I think: The deploy button URL on this end is just https://heroku.com/deploy - I believe Heroku looks at the referring page, sees that it's Github, retrieves the app.json file containing the rest of the configuration about the deployment and fills everything in from there. 

I don't have any problem with the deploy button here - just checking, are you clicking it from the Readme on GitHub here?

**Comment by adaptpatrick** [comment]
Hey @benjamin-hull, no dramas! We're all guilty of silly errors - it's part of being a programmer! 😂

Pleased to say it appears to be working as expected now! 🙌  I did have an issue with inputting an incorrect starting token originally, which I tried to update in the Config Vars in Heroku, but despite restarting the Dyno(s) it never seemed to make a difference. Instead I had to delete the Dyno and complete the process again (no biggie), which then worked when I entered the correct starting token. 

Thanks again for your help with this! 🙏

**Comment by benjamin-hull** [comment]
That's a good piece of info, thanks @adaptpatrick. 1.0.3 should now allow the user to force-refresh the token after an error, which should resolve the issue without needing to nuke the dyno and start again. Feel free to re-open if you have any more issues with this.
