### ISSUE TITLE
Initial app stopped working - now new one stuck on 'finish configuring' page

### ISSUE THREAD

**Issue by jimmyfisher** [companionstudio/instagram-token-agent#26]
Having a major issue that's breaking the functionality. I initially deployed the app on June 9. I was able to paste in my token that was generated by Facebook (following the tutorial steps). I implemented the script into my site and was able to get images.

Today, I noticed that images weren't showing up. Javascript console when using developer tools on my homepage reads:
`Error: api request error: 190 Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons`

This led me to Facebook where it appeared that 'due to inactivity', the app I had created in June had been disabled. I reactivated it and refreshed Heroku. No luck.

I then went through the steps again to get a new token via the FB token generator. I went to the 'settings' tab on Heroku and updated the 'STARTING_TOKEN'. Saved and relaunched - still no success.

Decided to make a new Heroku deployment (following the tutorial). Pasted in the latest token from FB and deployed. When I launched the new app, I get this screen:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/35467099/92309126-76fab300-ef68-11ea-8a2f-96fea6346367.png">

First of all, the two configuration values listed do not show up on Heroku. STARTING_TOKEN is there, but not INSTAGRAM_TOKEN. ALLOWED_DOMAINS is also not there.

So it now seems I either can get to my original Heroku app where it shows this screen:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/35467099/92309159-c2ad5c80-ef68-11ea-9c37-fc7140ac2295.png">

Or I can get to the new app, but can't get past the part where it tells me I need to finish configuring the agent.

The only other thing to note is on my **original** token agent, when I click on the token.json link on the page, it displays an old token (not the one I just updated under the STARTING_TOKEN variable). Not sure if there's a refresh time, but it's unclear either way.

Please let me know how I can get this to function properly as right now, my IG feed on my website is down.

Thanks!

**Desktop**
 - OS: MacOS X 10.14.6
 - Browser: Safari and Chrome Tested
 - Version: latest versions

**Comment by jimmyfisher** [comment]
I just tried manually adding these two:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/35467099/92309832-6cdbb300-ef6e-11ea-9945-8c066060bcc4.png">

Copy/pasted my STARTING_TOKEN value and then manually guessed to put my website URL. That worked - but not sure why those values aren't showing up when I click the 'deploy' button in the instructions on Heroku.

**Comment by jimmyfisher** [comment]
To further clarify (because all I had to do now was update my URL in my website code to the new Heroku app's URL), I now have all of these showing:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/35467099/92309964-584bea80-ef6f-11ea-9786-5a8066bd1e7f.png">
The bottom two were the ones I manually added. Is this going to function properly? And also, is there something beyond the 'Deploy' button that needs to be clicked/done for the proper config values to show up as options?

**Comment by benjamin-hull** [comment]
Hi @jimmyfisher - that's some good detective work! 

The setup screen was referring to INSTAGRAM_TOKEN, but should actually be STARTING_TOKEN. This is fixed in the release in the `starting-environment` branch. ALLOWED_DOMAINS is also prompted for on deploy now.

The issue with the app being disabled due to inactivity is a new one on me, and not mentioned in the docs that I've seen. I'll raise a separate issue to track that, thanks.

Could you try a fresh deployment from the button on the starting-environment branch here? https://github.com/companionstudio/instagram-token-agent/tree/starting-environment - it will ask for ALLOWED_DOMAINS on deploy, and includes some nicer error handling logging in case anything goes wrong during the deployment.

Let me know how that goes!

**Comment by benjamin-hull** [comment]
This is now fixed in 1.0.3+ - available for deploy/update from master.

**Comment by jimmyfisher** [comment]
Hey @benjamin-hull - thanks for looking into it!

I just ran it with the latest deploy and no problems anymore. Proper fields showing up for the deployment as well as functioning properly once the app gets built. Updated my website code and pulling in fine now. If you're interested: [https://www.flipsidenewyork.com](url)

Thanks again,
Jimmy
