### ISSUE TITLE
Clarity on Heroku needing Credit Card

### ISSUE THREAD

**Issue by jimmyfisher** [companionstudio/instagram-token-agent#3]
Hey there,

Commented on another user's post, but they closed the topic and just gave Heroku a credit card.

Trying to double check and confirm as a novice Heroku user that I'm not signing up for something where I will unintentionally be charged.

I understand the 'free' plan but the 'add-ons' are where I'm concerned... are those free also with this app or am I missing something?

When I click 'deploy' and following the app name instructions as well as the API from Facebook, this is what I'm getting:

<img width="711" alt="Screen Shot 2020-03-31 at 1 52 48 PM" src="https://user-images.githubusercontent.com/35467099/78189672-7a7d9180-7440-11ea-92ed-5358a01a7066.png">

<img width="406" alt="Screen Shot 2020-03-31 at 1 51 12 PM" src="https://user-images.githubusercontent.com/35467099/78189673-7b162800-7440-11ea-9ee0-a4ea8ece9c79.png">

Please let me know when possible. Would love to start trying to figure out how to implement with a Shopify theme I use, but just making sure I know what I'm signing up for.

Thanks!

**Comment by benjamin-hull** [comment]
Right - my apologies! I have only tested this with an established Heroku account, so I didn't realize you'd be asked for a credit card.

Yes, all the add-ons are on free plans, and shouldn't ever need anything more than those, so you won't be charged anything.

**Comment by benjamin-hull** [comment]
Addressed in 4bed93ace1c2cb5e69b1a4a622b458fdf1538652 - Thanks for the heads-up, @jimmyfisher !
